{{- if .Values.ingress.internalEnabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ required "app.name is required" .Values.app.name }}-internal
  namespace: {{ required "global.namespace is required" .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: viptt-app
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- with .Values.ingress.internal.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  ingressClassName: {{ required "ingress.internal.className is required" .Values.ingress.internal.className }}
  rules:
  - host: {{ required "ingress.internal.host is required" .Values.ingress.internal.host }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: {{ required "app.name is required" .Values.app.name }}
            port:
              number: {{ .Values.service.ports.https }}
{{- end }}
