{{- if and .Values.networkPolicies.enabled .Values.networkPolicies.egress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-networkpolicy-egress-{{ .Values.app.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: viptt-app
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      name: {{ .Values.app.name }}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  - to:
    - podSelector:
        matchLabels:
          name: {{ .Values.redis.name }}
    ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
  {{- range .Values.networkPolicies.egress.redisServiceCIDRs }}
  - to:
    - ipBlock:
        cidr: {{ . }}
    ports:
    - protocol: TCP
      port: {{ $.Values.redis.port }}
  {{- end }}
  {{- range .Values.networkPolicies.egress.externalHttpsCIDRs }}
  - to:
    - ipBlock:
        cidr: {{ . }}
    ports:
    - protocol: TCP
      port: 443
  {{- end }}
{{- end }}
