{{- if .Values.redis.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "viptt-app.commonLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Values.redis.name }}
        service: {{ .Values.redis.name }}
        app.kubernetes.io/name: redis
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- include "viptt-app.commonLabels" . | nindent 8 }}
    spec:
      {{- if .Values.podAntiAffinity.enabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: redis
                    app.kubernetes.io/instance: {{ .Release.Name }}
                topologyKey: topology.kubernetes.io/zone
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: redis
        image: {{ required "redis.image is required when redis.enabled=true" .Values.redis.image }}
        ports:
        - containerPort: {{ .Values.redis.port }}
          name: redis
        {{- if .Values.redis.healthChecks.enabled }}
        livenessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: {{ .Values.redis.healthChecks.initialDelaySeconds }}
          periodSeconds: {{ .Values.redis.healthChecks.periodSeconds }}
        readinessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: {{ .Values.redis.healthChecks.initialDelaySeconds }}
          periodSeconds: {{ .Values.redis.healthChecks.periodSeconds }}
        {{- end }}
        volumeMounts:
        - mountPath: /var/lib/redis
          name: data
        - mountPath: /usr/local/etc/redis
          name: redis-config
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
      volumes:
      - name: data
        emptyDir: {}
      - name: redis-config
        configMap:
          name: redis-cache-config
{{- end }}
