---
apiVersion: v1
kind: ConfigMap
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  DISALLOW_INDEXING: "true"
  name: {{ .APP_NAME }}-configmap-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: {{ .APP_NAME }}-configmap
  {{ end }}
  namespace: {{ .KUBE_NAMESPACE }}
  labels:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    DISALLOW_INDEXING: "true"
    name: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}
    {{ else }}
    name: {{ .APP_NAME }}
    {{ end }}
data:
{{ file .CONFIGMAP_VALUES | indent 2 }}
